name: flutter_gsmpay_interview
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 1.0.8
  freezed_annotation: 2.4.4
  injectable: 2.3.2
  flutter_bloc: 9.1.0
  get_it: 7.6.7
  intl: 0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  build_runner: 2.4.15
  injectable_generator: 2.4.1
  freezed: 2.5.2
  intl_utils: 2.8.8
  dotted_border: 2.1.0
  image_picker: 1.1.2

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Dana
      fonts:
        - asset: assets/font/dana_black.ttf
          weight: 900
        - asset: assets/font/dana_extra_bold.ttf
          weight: 800
        - asset: assets/font/dana_bold.ttf
          weight: 700
        - asset: assets/font/dana_demi_bold.ttf
          weight: 600
        - asset: assets/font/dana_medium.ttf
          weight: 500
        - asset: assets/font/dana_regular.ttf
          weight: 400
        - asset: assets/font/dana_light.ttf
          weight: 300
        - asset: assets/font/dana_ultra_light.ttf
          weight: 200
        - asset: assets/font/dana_thin.ttf
          weight: 100


flutter_intl:
  enabled: true
  main_locale: fa
  arb-dir: lib/l10n
  template-arb-file: app_fa.arb