name: flutter_gsmpay_interview
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 1.0.8
  freezed_annotation: 2.4.4
  injectable: 2.3.2
  flutter_bloc: 9.1.0
  get_it: 7.6.7
  intl: 0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  build_runner: 2.4.15
  injectable_generator: 2.4.1
  freezed: 2.5.2
  intl_utils: 2.8.8

flutter:
  uses-material-design: true
  generate: true

flutter_intl:
  enabled: true
  main_locale: en
  arb-dir: lib/l10n
  template-arb-file: app_en.arb